# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vlad/Programming/ipp/project_middle_ages/IPP-ws374078

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vlad/Programming/ipp/project_middle_ages/IPP-ws374078

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad/Programming/ipp/project_middle_ages/IPP-ws374078/CMakeFiles /home/vlad/Programming/ipp/project_middle_ages/IPP-ws374078/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad/Programming/ipp/project_middle_ages/IPP-ws374078/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named middle_ages

# Build rule for target.
middle_ages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 middle_ages
.PHONY : middle_ages

# fast build rule for target.
middle_ages/fast:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/build
.PHONY : middle_ages/fast

src/engine.o: src/engine.c.o

.PHONY : src/engine.o

# target to build an object file
src/engine.c.o:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/engine.c.o
.PHONY : src/engine.c.o

src/engine.i: src/engine.c.i

.PHONY : src/engine.i

# target to preprocess a source file
src/engine.c.i:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/engine.c.i
.PHONY : src/engine.c.i

src/engine.s: src/engine.c.s

.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.c.s:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/engine.c.s
.PHONY : src/engine.c.s

src/middle_ages.o: src/middle_ages.c.o

.PHONY : src/middle_ages.o

# target to build an object file
src/middle_ages.c.o:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/middle_ages.c.o
.PHONY : src/middle_ages.c.o

src/middle_ages.i: src/middle_ages.c.i

.PHONY : src/middle_ages.i

# target to preprocess a source file
src/middle_ages.c.i:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/middle_ages.c.i
.PHONY : src/middle_ages.c.i

src/middle_ages.s: src/middle_ages.c.s

.PHONY : src/middle_ages.s

# target to generate assembly for a file
src/middle_ages.c.s:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/middle_ages.c.s
.PHONY : src/middle_ages.c.s

src/parse.o: src/parse.c.o

.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i

.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s

.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) -f CMakeFiles/middle_ages.dir/build.make CMakeFiles/middle_ages.dir/src/parse.c.s
.PHONY : src/parse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... middle_ages"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/middle_ages.o"
	@echo "... src/middle_ages.i"
	@echo "... src/middle_ages.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

